import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const levels=[
 {id:1,title:'READ THE MARKET',range:[1,5]},
 {id:2,title:'LIQUIDITY HUNTER',range:[6,10]},
 {id:3,title:'THE LIQUIDITY RAID',range:[11,15]}
];
const missions=[
{id:1,level:1,title:'Meet the Candle',type:'choice',question:'Which part of a candle shows the highest price?',options:['Open','Close','High','Low'],answer:'High',explanation:'The High is the highest price reached during that candle. The wick can reach it even when the candle closes somewhere else.'},
{id:2,level:1,title:'Bull or Bear?',type:'choice',question:'A candle opens at 100 and closes at 108. What is it?',options:['Bullish','Bearish','Doji','Impossible to know'],answer:'Bullish',explanation:'When Close is above Open, buyers pushed price higher during that candle. That makes it bullish.'},
{id:3,level:1,title:'Who Won?',type:'choice',question:'Open: 20,000. Close: 20,080. Who controlled the candle?',options:['Sellers','Buyers','Nobody','Liquidity'],answer:'Buyers',explanation:'The candle closed above its Open, so buyers won that candle. This does not mean the entire market is bullish.'},
{id:4,level:1,title:'Put the Market in Order',type:'order',question:'Build the sequence from PAST to NOW.',instruction:'Tap the candles in the order they happened. Start with the oldest candle. Do NOT choose based on green/red color.',cards:['A','B','C','D'],sequence:['C','A','D','B'],explanation:'Price develops through time. Reading PAST → NOW lets you understand what happened before the current candle.'},
{id:5,level:1,title:'Speed Reader',type:'choice',question:'You briefly see 20 candles. They begin near 100 and finish near 106. The candles are mixed, but more are green than red. What is the overall direction?',options:['Higher','Lower','Sideways','Unknown'],answer:'Higher',explanation:'The ending area is above the starting area. Individual candles can pull back, but the overall move is higher.'},
{id:6,level:2,title:'Find the High',type:'choice',question:'Which price point is the High of this move?',options:['Top extreme','Middle','Bottom extreme','Open'],answer:'Top extreme',visual:'high',explanation:'High means the highest price reached. Do not use candle color to decide it.'},
{id:7,level:2,title:'Find the Low',type:'choice',question:'Which price point is the Low of this move?',options:['Top extreme','Middle','Bottom extreme','Close'],answer:'Bottom extreme',visual:'low',explanation:'Low means the lowest price reached. Focus on the actual price extreme.'},
{id:8,level:2,title:'Equal Highs',type:'choice',question:'Which pair shows Equal Highs?',options:['A + C','B + D','A + D','B + C'],answer:'B + D',visual:'eqhigh',explanation:'Equal Highs are repeated highs around the same price level. Traders may watch the area above them for liquidity.'},
{id:9,level:2,title:'Equal Lows',type:'choice',question:'Which pair shows Equal Lows?',options:['A + C','B + D','A + D','B + C'],answer:'A + C',visual:'eqlow',explanation:'Equal Lows are repeated lows around the same price level. Traders may watch the area below them for liquidity.'},
{id:10,level:2,title:'Liquidity or Noise?',type:'choice',question:'Which area gives the clearest liquidity clue?',options:['A: one isolated high','B: three highs near the same level','C: one large green candle','D: the candle with the longest body'],answer:'B: three highs near the same level',visual:'liquidity',explanation:'Liquidity is not simply the highest or lowest candle. Repeated, obvious levels are more meaningful because many traders can see them.'},
{id:11,level:3,title:'Did Liquidity Get Swept?',type:'choice',question:'Price runs above equal highs and then trades back below them. What happened?',options:['Liquidity sweep','Clean continuation','Nothing happened','FVG formed'],answer:'Liquidity sweep',visual:'sweep',explanation:'Price traded beyond an obvious high and then returned below it. That is the behavior we are training you to recognize as a liquidity sweep.'},
{id:12,level:3,title:'The Fake Break',type:'choice',question:'Which scenario is more consistent with a liquidity raid?',options:['Breaks the high and keeps expanding higher','Trades above the high, rejects, then returns below it','Moves sideways without touching the high','Drops before reaching the high'],answer:'Trades above the high, rejects, then returns below it',visual:'fake',explanation:'A raid is about what price does after taking the level. A break alone is not enough to call it a reversal.'},
{id:13,level:3,title:'Judas Swing',type:'choice',question:'At the start of the session, price first runs toward a visible liquidity pool, then reverses sharply. What should you identify first?',options:['Liquidity grab','Entry','Take profit','Random movement'],answer:'Liquidity grab',visual:'judas',explanation:'The first job is to recognize the liquidity event. Do not jump straight to an entry before the market gives evidence.'},
{id:14,level:3,title:'Patience Test',type:'choice',question:'Price reaches liquidity, but there is no confirmation yet. What is the best process?',options:['Enter immediately','Wait for confirmation','Move the stop wider','Double the risk'],answer:'Wait for confirmation',visual:'patience',explanation:'Reaching liquidity is a location, not automatically an entry. Wait for the market to show the reaction or structure evidence you require.'},
{id:15,level:3,title:'Choose the Liquidity',type:'choice',question:'Which level is the clearest potential liquidity target?',options:['A single random wick','Two obvious equal highs','A candle body in the middle','A random midpoint'],answer:'Two obvious equal highs',visual:'target',explanation:'Repeated, obvious highs create a clearer pool to monitor than a random price point.'}
];

function MiniChart({kind}){return <div className={'chart '+(kind||'')}><div className="grid"></div><div className="line l1"></div><div className="line l2"></div><div className="line l3"></div><div className="label top">HIGH</div><div className="label bot">LOW</div>{kind==='eqhigh'&&<div className="dots">●────────●</div>}{kind==='eqlow'&&<div className="dots lowdots">●────────●</div>}{kind==='sweep'&&<div className="sweepline">↑ SWEEP ↓</div>}{kind==='judas'&&<div className="judasline">LIQUIDITY → ↘</div>}</div>}
function App(){
 const [idx,setIdx]=useState(0),[xp,setXp]=useState(0),[selected,setSelected]=useState(null),[order,setOrder]=useState([]),[done,setDone]=useState(false),[showLevels,setShowLevels]=useState(false);
 const m=missions[idx]; const lvl=levels.find(l=>idx+1>=l.range[0]&&idx+1<=l.range[1]);
 function resetMission(){setSelected(null);setOrder([])}
 function choose(o){if(selected)return;setSelected(o);if(o===m.answer)setXp(x=>x+100)}
 function tapOrder(c){if(order.includes(c))return; const next=[...order,c]; setOrder(next); if(c!==m.sequence[next.length-1]){setSelected('WRONG');setTimeout(()=>{setSelected(null);setOrder([])},900)} else if(next.length===m.sequence.length){setSelected('CORRECT');setXp(x=>x+100)}}
 function next(){if(idx===missions.length-1){setDone(true);return}setIdx(i=>i+1);resetMission()}
 if(done)return <main className="app"><section className="card result"><div className="badge">LEVEL 3 COMPLETE</div><h1>Liquidity Raider</h1><p>You completed the first 15 missions.</p><div className="xp">+{xp} XP</div><button onClick={()=>{setDone(false);setIdx(0);setXp(0);resetMission()}}>Replay</button></section></main>;
 return <main className="app"><header><div><div className="brand">TRADING LEVELING</div><div className="subtitle">Train your eyes. Level your trading.</div></div><div className="xp">XP {xp}</div></header>
 <div className="levelbar"><button className="levelbtn" onClick={()=>setShowLevels(!showLevels)}>LEVEL {lvl.id} · {lvl.title} ▾</button>{showLevels&&<div className="levels">{levels.map(l=><div key={l.id} className={l.id===lvl.id?'current':''}>Level {l.id} — {l.title}</div>)}</div>}</div>
 <section className="progress">{missions.map((x,i)=><span key={x.id} className={i<=idx?'active':''}>{i+1}</span>)}</section>
 <section className="card"><div className="mission">MISSION {m.id} / 15</div><h1>{m.title}</h1>{m.instruction&&<div className="instruction">🎯 {m.instruction}</div>}{m.visual&&<MiniChart kind={m.visual}/>}<p className="question">{m.question}</p>
 {m.type==='order'?<div className="orderArea"><div className="ordertrack"><span>PAST</span><div className="arrow"></div><span>NOW</span></div><div className="ordercards">{m.cards.map(c=><button key={c} className={order.includes(c)?'picked':''} onClick={()=>tapOrder(c)}>{c}{order.includes(c)&&<b>{order.indexOf(c)+1}</b>}</button>)}</div></div>:<div className="options">{m.options.map(o=><button key={o} className={selected?(o===m.answer?'correct':o===selected?'wrong':''):''} onClick={()=>choose(o)}>{o}</button>)}</div>}
 {(selected==='CORRECT'||selected==='WRONG'||(selected&&m.type!=='order'))&&<div className={'feedback '+((selected==='CORRECT'||selected===m.answer)?'good':'bad')}><strong>{(selected==='CORRECT'||selected===m.answer)?'Correct!':'Not quite.'}</strong><p>{m.explanation}</p>{selected!=='WRONG'&&<button onClick={next}>{idx===missions.length-1?'Finish Level':'Next Mission →'}</button>}</div>}
 </section></main>
}
createRoot(document.getElementById('root')).render(<App/>);
